### ISSUE TITLE
IconBadge won't update correctly when mark_seen = true

### ISSUE THREAD

**Issue by dgarciamuria** [GetStream/react-native-activity-feed#93] opened 2019-12-26 19:35 UTC
**Setup:**
- iOS
- React Native
- React Native Version: 0.61.2
- `react-native-activity-feed@0.8.14`
- `getstream@4.2.5`

Hi everyone. So I have a basic application with a `Notifications` screen. There's a `IconBadge` next to the tab button that takes you to that screen.
Whenever I react to an activity, a notification is created and the `IconBadge` reflects that and increments the counter, but when I navigate to the screen `<NotificationFeed options={{mark_seen: true}}` /> loads and displays all notification correctly but `IconBadge` doesn't get the faye update and the counter gets out of sync. If I refresh the app, the badge updates and displays the correct number of notifications (0) so `mark_seen: true` travels with the request correctly
Any ideas of what I might be doing wrong?

Thanks!

**Comment by jaapbakker88** [comment] 2019-12-30 12:21
@dgarciamuria can you check in your Notifications screen if anything happens in 
* componentWIllMount
* componentDidMount
* componentWillUpdate

**Comment by dgarciamuria** [comment] 2020-01-02 17:40
@jaapbakker88 I ended up building a custom implementation that uses `context` and gives you a handler to manually refresh notifications. I first tried to accomplish that by re-mountaing `IconBadge` (since that happens in `componentDidMount`) but it was far from ideal. But I can confirm that a subscription to a notifications feed is not receiving the event when all notifications are marked as seen.
This is not related to `react-native-activity-feed` but rather to `getstream-js`, it might be worth to open an issue in that repo.

**Comment by jaapbakker88** [comment] 2020-01-03 08:09
Thank you for reporting back. I'm going to close this issue and investigate further in `getstream-js`

**Closed by jaapbakker88** 2020-01-03 08:09 UTC

**Comment by wodow** [comment] 2021-03-29 10:35
This appears to still be an issue in `react-native-activity-feed-core` v1.0.1

Please could this be reopened? Regardless of whether the issue is really in `getstream-js`, it still manifests here.

**Comment by wodow** [comment] 2021-03-29 10:50
Following a little more searching, I see https://github.com/GetStream/react-activity-feed/issues/102#issuecomment-640538623 suggests that it depends on `sharedFeeds`, so I will look into that.
