### ISSUE TITLE
Infinite loading spinner

### ISSUE THREAD

**Issue by Ingibjorg** [GetStream/react-native-activity-feed#5] opened 2018-10-24 18:34 UTC
The pull to refresh is not working as expected. If I scroll down the feed and paginate once or twice and scroll back up to top and pull to refresh, the loading spinner spins infinitely and does not update the feed.

**Comment by Ingibjorg** [comment] 2018-10-29 22:52
@JelteF and @thesyncim I updated the issue description. I'm only seeing this behaviour after paginating when the `loadNextPage` function is called and I try to pull to refresh.

**Comment by JelteF** [comment] 2018-10-30 10:14
That's strange. Can you give some more info on your setup?
- Do you use expo or normal react native?
- Is this on iOS or Android?

**Comment by Ingibjorg** [comment] 2018-10-30 16:57
Normal React Native on iOS. Here's my setup:

```
<StreamApp
        style={{ flex: 1 }}
        apiKey={Config.GETSTREAM_API_KEY}
        appId={Config.GETSTREAM_APP_ID}
        userId={userId}
        token={streamToken}
        errorHandler={() => {}}
      >
        <FlatFeed feedGroup="user" userId={feedId} Activity={({ activity }) => this.activityItem(activity)} />
</StreamApp>
```

**Comment by accordis** [comment] 2018-11-02 18:03
@JelteF Hi, still wondering about this one. The project in question is using this library, but not the collections portion for client-side enrichment (though, I don't see how this would cause that issue). The issue occurs when scrolling down a significant way, then scrolling back up to the top.

**Comment by JelteF** [comment] 2018-11-05 10:59
We've been able to reproduce this issue. It seems that https://github.com/facebook/react-native/issues/5839 is the root cause of this. I've implemented a workaround for that now and in our testing it seems that it fixes the issue indeed. This workaround is now released as v0.6.8 of the library. I'll close this issue, but feel free to reopen it if the workaround doesn't work for you.

**Closed by JelteF** 2018-11-05 10:59 UTC

**Comment by dolsem** [comment] 2019-01-20 21:43
I've encountered this issue multiple times as well. In my case, I load the app with empty feed, then subscribe to another feed that has activities in it and pull to refresh. About 8/10 times it works just fine, but sometimes I see infinite loader. I'm using the latest library versions (expo-activity-feed@0.8.5, getstream@4.1.0). Seems to happen randomly. Any idea why?

**Comment by JelteF** [comment] 2019-01-22 10:40
@dolsem could you create a new issue for your issue, because it seems a bit different.
